### ISSUE TITLE
training and testing

### ISSUE THREAD

**Issue by ak9250** [zhangzjn/FaceSwapNet#1]
when will training and testing code and well as pretrained model be added thanks

**Comment by Zzlongjuanfeng** [comment]
Maybe Sept. 4 (the date of NeurIPS notification), and we hope so :)

**Comment by ak9250** [comment]
@Zzlongjuanfeng ok great, looking forward to test it out soon

**Comment by skunkwerk** [comment]
really looking forward to this, thank you

**Comment by ak9250** [comment]
Hi will the code and pretrained model be released sept 4th?

**Comment by zhangzjn** [comment]
@ak9250 I‘m so sorry  for the delay in releasing the code, and we will open our code by October at the latest, thank you☺
