### ISSUE TITLE
Cannot find the supplementary material

### ISSUE THREAD

**Issue by aminm2a** [zhangzjn/FaceSwapNet#2]
Can you point me to a link of the paper's supplementary material ?
Thanks

**Comment by zhangzjn** [comment]
> Can you point me to a link of the paper's supplementary material ?
> Thanks
Sorry for the late reply, now you can find it on [](https://drive.google.com/open?id=1f1thm4wvRbBgwZfkanG2Pu1M47qeSKUd).

**Comment by zhangzjn** [comment]
@aminm2a Sorry for the late reply, now you can find it on [https://drive.google.com/open?id=1f1thm4wvRbBgwZfkanG2Pu1M47qeSKUd](url)

**Comment by aminm2a** [comment]
Thank you :)

**Comment by aminm2a** [comment]
according to the paper, synthesis on faces not in the training set are not good. The model cannot generalize well, any idea on the problem  ?

**Comment by zhangzjn** [comment]
@aminm2a Sorry for the late reply, according the results of experiments, we think the main reason is training set is small, for not existing (weakly) paired dataset. And so the network may remember some common features appeared in the training set, which is bad for face generations outside the RaFD dataset. Some experiments' analyses in the paper also show that our proposed model has a  pretty good generalization ability. And we will find, maybe build, a new dataset for this any-to-any face swap task in the future.
