### ISSUE TITLE
Input to the landmark encoder

### ISSUE THREAD

**Issue by lubovbyc** [zhangzjn/FaceSwapNet#4]
Hi,

According to the paper, the output of the Landmark Swapper is a 212-dim vector. However, the input to the Landmark Encoder is a feature map of shape (h/4, w/4, 1). Do you add additional layers to mitigate this gap,  or directly transform the coordinates with zero-one matrix or heatmap?

Thanks

**Comment by zhangzjn** [comment]
@lubovbyc I use 'cv2.circle' function (with params radius=1, color=255, thickness=2) to transform the 212-dim vector to a 256*256 image, and then resize it to 64*64 by torchvision.transforms.Resize(). Good luck~

**Comment by lubovbyc** [comment]
Got it. Thanks:)
